### ISSUE TITLE
jsx3 support

### ISSUE THREAD

**Issue by ixzzd** [FiberJW/reason-expo#9]
Hi! Do you have plans to add bindings for jsx3?

**Comment by FiberJW** [comment]
Reason Hooks support will land here when the next Expo SDK is released, which will include hooks support. Expo currently doesn't support Hooks officially, so enabling jsx3 in a ReasonExpo app may be futile at the moment. I could enable JSX 3 so that would enable the new React.* namespace, but that would tempt users to start using the Hooks features which would most likely break projects. 👍

**Comment by ixzzd** [comment]
Thanks! Nice to know that you have plans to land it. Thanks for your awesome bindings!
